-- Relatório anual de gestão da ouvidoria (Lei 13.460/2017, arts. 14, II, e 15), que também cumpre a
-- estatística anual de pedidos LAI (Lei 12.527/2011, art. 30, III). A análise dos pontos recorrentes e as
-- providências adotadas (art. 15, III e IV) são escritas pela ouvidoria; os números são calculados pelo
-- sistema e congelados em estatisticas na publicação, para o documento oficial não mudar depois.
CREATE TABLE relatorio_gestao (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id                BIGINT      NOT NULL REFERENCES municipio (id),
    ano                         INTEGER     NOT NULL,
    analise_pontos_recorrentes  TEXT,
    providencias_adotadas       TEXT,
    -- Nulo enquanto rascunho; preenchido na publicação
    estatisticas                JSONB,
    publicado_em                TIMESTAMPTZ,
    publicado_por_id            BIGINT REFERENCES usuario (id),
    atualizado_em               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_relatorio_gestao UNIQUE (municipio_id, ano),
    CONSTRAINT ck_relatorio_publicacao CHECK (
        (publicado_em IS NULL AND estatisticas IS NULL AND publicado_por_id IS NULL)
        OR (publicado_em IS NOT NULL AND estatisticas IS NOT NULL AND publicado_por_id IS NOT NULL
            AND analise_pontos_recorrentes IS NOT NULL AND providencias_adotadas IS NOT NULL)
    )
);
