-- Tenant: tudo que é específico de uma prefeitura aponta para cá
CREATE TABLE municipio (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    uf          VARCHAR(2)   NOT NULL,
    codigo_ibge VARCHAR(7)   NOT NULL UNIQUE,
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_municipio_codigo_ibge CHECK (codigo_ibge ~ '^[0-9]{7}$')
);

CREATE TABLE secretaria (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT       NOT NULL REFERENCES municipio (id),
    nome         VARCHAR(150) NOT NULL,
    sigla        VARCHAR(20)  NOT NULL,
    email        VARCHAR(150),
    ativa        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_secretaria_sigla UNIQUE (municipio_id, sigla),
    -- Alvo das FKs compostas: garante no banco que quem aponta para a secretaria é do mesmo município
    CONSTRAINT uk_secretaria_municipio UNIQUE (id, municipio_id)
);

CREATE TABLE perfil (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    senha_hash    VARCHAR(100) NOT NULL,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    perfil_id     BIGINT       NOT NULL REFERENCES perfil (id),
    -- NULL só para ADMIN_PLATAFORMA (validado no service, CHECK não enxerga outra tabela)
    municipio_id  BIGINT REFERENCES municipio (id),
    -- Preenchido só para SERVIDOR
    secretaria_id BIGINT,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_usuario_secretaria FOREIGN KEY (secretaria_id, municipio_id)
        REFERENCES secretaria (id, municipio_id)
);

CREATE INDEX ix_usuario_municipio ON usuario (municipio_id);
