CREATE TABLE cidadao (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT       NOT NULL REFERENCES municipio (id),
    -- NULL quando o cidadão não tem login (ex.: manifestação registrada presencialmente)
    usuario_id   BIGINT UNIQUE REFERENCES usuario (id),
    nome         VARCHAR(150) NOT NULL,
    cpf          VARCHAR(11),
    email        VARCHAR(150),
    telefone     VARCHAR(20),
    criado_em    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_cidadao_cpf UNIQUE (municipio_id, cpf),
    CONSTRAINT uk_cidadao_municipio UNIQUE (id, municipio_id),
    CONSTRAINT ck_cidadao_cpf CHECK (cpf ~ '^[0-9]{11}$')
);

-- Tipos são nacionais (definidos pelas leis 13.460 e 12.527), não por município
CREATE TABLE tipo_manifestacao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(30) NOT NULL UNIQUE,
    nome            VARCHAR(60) NOT NULL,
    categoria       VARCHAR(10) NOT NULL,
    permite_anonimo BOOLEAN     NOT NULL,
    permite_recurso BOOLEAN     NOT NULL,
    CONSTRAINT ck_tipo_categoria CHECK (categoria IN ('OUVIDORIA', 'LAI'))
);

-- municipio_id NULL = regra federal padrão; linha com município sobrescreve (art. 45 da LAI)
CREATE TABLE prazo_legal (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_manifestacao_id      BIGINT      NOT NULL REFERENCES tipo_manifestacao (id),
    municipio_id              BIGINT REFERENCES municipio (id),
    dias_resposta             INTEGER     NOT NULL,
    permite_prorrogacao       BOOLEAN     NOT NULL,
    dias_prorrogacao          INTEGER,
    dias_interposicao_recurso INTEGER,
    dias_julgamento_recurso   INTEGER,
    atualizado_em             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_prazo_dias_resposta CHECK (dias_resposta > 0),
    CONSTRAINT ck_prazo_prorrogacao CHECK (
        (permite_prorrogacao AND dias_prorrogacao > 0)
        OR (NOT permite_prorrogacao AND dias_prorrogacao IS NULL)
    ),
    -- Prazos de recurso andam juntos: ou o tipo tem fase recursal completa, ou não tem
    CONSTRAINT ck_prazo_recurso CHECK (
        (dias_interposicao_recurso > 0 AND dias_julgamento_recurso > 0)
        OR (dias_interposicao_recurso IS NULL AND dias_julgamento_recurso IS NULL)
    )
);

-- Uma regra nacional por tipo e no máximo uma por (tipo, município).
-- Índices parciais em vez de NULLS NOT DISTINCT para funcionar também em PostgreSQL < 15.
CREATE UNIQUE INDEX uk_prazo_nacional ON prazo_legal (tipo_manifestacao_id) WHERE municipio_id IS NULL;
CREATE UNIQUE INDEX uk_prazo_municipio ON prazo_legal (tipo_manifestacao_id, municipio_id) WHERE municipio_id IS NOT NULL;
