CREATE TABLE manifestacao (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id         BIGINT       NOT NULL REFERENCES municipio (id),
    protocolo            VARCHAR(30)  NOT NULL UNIQUE,
    tipo_manifestacao_id BIGINT       NOT NULL REFERENCES tipo_manifestacao (id),
    -- NULL = manifestação anônima
    cidadao_id           BIGINT,
    -- NULL até o encaminhamento
    secretaria_id        BIGINT,
    assunto              VARCHAR(200) NOT NULL,
    descricao            TEXT         NOT NULL,
    status               VARCHAR(20)  NOT NULL,
    data_abertura        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Calculada na abertura a partir do PrazoLegal vigente; mudança posterior de lei não altera
    data_limite          DATE         NOT NULL,
    prorrogada           BOOLEAN      NOT NULL DEFAULT FALSE,
    data_encerramento    TIMESTAMPTZ,
    CONSTRAINT ck_manifestacao_status CHECK (status IN (
        'RECEBIDA', 'EM_ANALISE', 'ENCAMINHADA', 'RESPONDIDA', 'EM_RECURSO', 'ENCERRADA', 'ARQUIVADA'
    )),
    CONSTRAINT fk_manifestacao_cidadao FOREIGN KEY (cidadao_id, municipio_id)
        REFERENCES cidadao (id, municipio_id),
    CONSTRAINT fk_manifestacao_secretaria FOREIGN KEY (secretaria_id, municipio_id)
        REFERENCES secretaria (id, municipio_id)
);

CREATE INDEX ix_manifestacao_municipio_status ON manifestacao (municipio_id, status);
CREATE INDEX ix_manifestacao_secretaria ON manifestacao (secretaria_id);
CREATE INDEX ix_manifestacao_cidadao ON manifestacao (cidadao_id);

-- Contador do sequencial do protocolo (ANO-IBGE-SEQUENCIAL), reinicia a cada ano.
-- Não é entidade: é incrementado por um único INSERT ... ON CONFLICT DO UPDATE ... RETURNING.
CREATE TABLE protocolo_sequencia (
    municipio_id BIGINT  NOT NULL REFERENCES municipio (id),
    ano          INTEGER NOT NULL,
    ultimo       INTEGER NOT NULL,
    PRIMARY KEY (municipio_id, ano)
);
