-- Filhos da manifestação não têm municipio_id: o isolamento é sempre via join com manifestacao

CREATE TABLE anexo (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestacao_id BIGINT       NOT NULL REFERENCES manifestacao (id),
    nome_arquivo    VARCHAR(255) NOT NULL,
    content_type    VARCHAR(100) NOT NULL,
    tamanho         BIGINT       NOT NULL,
    conteudo        BYTEA        NOT NULL,
    -- NULL quando enviado junto com manifestação anônima
    enviado_por_id  BIGINT REFERENCES usuario (id),
    enviado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_anexo_tamanho CHECK (tamanho > 0 AND tamanho <= 5242880)
);

CREATE INDEX ix_anexo_manifestacao ON anexo (manifestacao_id);

-- Histórico de negócio: uma linha por transição de status (ou prorrogação, que não muda status)
CREATE TABLE tramite (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestacao_id       BIGINT      NOT NULL REFERENCES manifestacao (id),
    -- NULL no registro da abertura
    status_anterior       VARCHAR(20),
    status_novo           VARCHAR(20) NOT NULL,
    usuario_id            BIGINT REFERENCES usuario (id),
    secretaria_destino_id BIGINT REFERENCES secretaria (id),
    descricao             TEXT,
    registrado_em         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_tramite_manifestacao ON tramite (manifestacao_id);

-- 1:N porque recurso deferido gera nova resposta
CREATE TABLE resposta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manifestacao_id BIGINT      NOT NULL REFERENCES manifestacao (id),
    usuario_id      BIGINT      NOT NULL REFERENCES usuario (id),
    secretaria_id   BIGINT      NOT NULL REFERENCES secretaria (id),
    texto           TEXT        NOT NULL,
    respondida_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_resposta_manifestacao ON resposta (manifestacao_id);

-- Só pedidos LAI (tipo.permite_recurso). Instância única: um recurso por resposta.
CREATE TABLE recurso (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resposta_id            BIGINT      NOT NULL UNIQUE REFERENCES resposta (id),
    justificativa          TEXT        NOT NULL,
    status                 VARCHAR(15) NOT NULL DEFAULT 'PENDENTE',
    interposto_em          TIMESTAMPTZ NOT NULL DEFAULT now(),
    data_limite_julgamento DATE        NOT NULL,
    decisao                TEXT,
    julgado_por_id         BIGINT REFERENCES usuario (id),
    julgado_em             TIMESTAMPTZ,
    CONSTRAINT ck_recurso_status CHECK (status IN ('PENDENTE', 'DEFERIDO', 'INDEFERIDO')),
    CONSTRAINT ck_recurso_julgamento CHECK (
        (status = 'PENDENTE' AND julgado_em IS NULL AND julgado_por_id IS NULL)
        OR (status <> 'PENDENTE' AND julgado_em IS NOT NULL AND julgado_por_id IS NOT NULL AND decisao IS NOT NULL)
    )
);
