-- Duas obrigações numa tabela:
--  1. Registro de acesso a aplicação (Marco Civil, art. 15): IP, data e hora, guardados sob sigilo por 6 meses
--     e entregues só por ordem judicial. Depois disso o IP é apagado por rotina diária (LGPD art. 16).
--  2. Trilha de quem fez o quê e de quem acessou a identidade de um manifestante (LGPD art. 37;
--     Decreto 10.153, art. 6º, § 3º). Essa parte fica, sem o IP.
-- Nenhuma rota da API lê esta tabela.
CREATE TABLE auditoria (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id  BIGINT REFERENCES municipio (id),
    -- Nulo em ação anônima (denúncia sem login, consulta pública)
    usuario_id    BIGINT REFERENCES usuario (id),
    acao          VARCHAR(30)  NOT NULL,
    entidade      VARCHAR(30),
    entidade_id   BIGINT,
    detalhe       VARCHAR(255),
    ip            VARCHAR(45),
    registrado_em TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_auditoria_entidade ON auditoria (entidade, entidade_id);
-- Acelera o expurgo diário dos IPs vencidos
CREATE INDEX ix_auditoria_ip_registrado ON auditoria (registrado_em) WHERE ip IS NOT NULL;
