-- Dias sem expediente para a contagem de prazo: vencimento em dia sem expediente passa ao primeiro dia útil
-- seguinte (Lei 9.784/1999, art. 66, § 1º). municipio_id NULL = feriado nacional; com município = feriado
-- estadual, municipal ou ponto facultativo com suspensão do expediente, cadastrado pela prefeitura.
-- anual = repete todo ano no mesmo dia e mês (a coluna data guarda a primeira ocorrência).
CREATE TABLE feriado (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT REFERENCES municipio (id),
    data         DATE         NOT NULL,
    anual        BOOLEAN      NOT NULL,
    descricao    VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX uk_feriado_nacional ON feriado (data) WHERE municipio_id IS NULL;
CREATE UNIQUE INDEX uk_feriado_municipal ON feriado (municipio_id, data) WHERE municipio_id IS NOT NULL;

-- Feriados nacionais de data fixa: Lei 662/1949, art. 1º (redação da Lei 10.607/2002); Lei 6.802/1980;
-- Lei 14.759/2023. Sexta-Feira da Paixão e demais feriados religiosos são municipais (Lei 9.093/1995, art. 2º)
-- e a data magna do Estado vem de lei estadual (art. 1º, II): a prefeitura cadastra pela API.
INSERT INTO feriado (municipio_id, data, anual, descricao) VALUES
    (NULL, DATE '2000-01-01', TRUE, 'Confraternização Universal (Lei 662/1949)'),
    (NULL, DATE '2000-04-21', TRUE, 'Tiradentes (Lei 662/1949)'),
    (NULL, DATE '2000-05-01', TRUE, 'Dia do Trabalho (Lei 662/1949)'),
    (NULL, DATE '2000-09-07', TRUE, 'Independência do Brasil (Lei 662/1949)'),
    (NULL, DATE '2000-10-12', TRUE, 'Nossa Senhora Aparecida (Lei 6.802/1980)'),
    (NULL, DATE '2000-11-02', TRUE, 'Finados (Lei 662/1949)'),
    (NULL, DATE '2000-11-15', TRUE, 'Proclamação da República (Lei 662/1949)'),
    (NULL, DATE '2023-11-20', TRUE, 'Dia Nacional de Zumbi e da Consciência Negra (Lei 14.759/2023)'),
    (NULL, DATE '2000-12-25', TRUE, 'Natal (Lei 662/1949)');
